# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConsoleIr < Formula
  desc "Terminal-first OCSF-native incident response manager for security analysts"
  homepage "https://github.com/Ashfaaq98/ocsf-console-ir"
  version "0.1.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ashfaaq98/ocsf-console-ir/releases/download/v0.1.0/console-ir_0.1.0_macOS_amd64.tar.gz"
      sha256 "5c81823b5af6e6ad2097cc01f673cae192963fb7cb49a2d1918b5c8b6773772e"

      define_method(:install) do
        bin.install "console-ir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ashfaaq98/ocsf-console-ir/releases/download/v0.1.0/console-ir_0.1.0_macOS_arm64.tar.gz"
      sha256 "062a1aadd44c9388201fb12dfdedde36ffa9e7e5cfb282d87f138c89a708cb3f"

      define_method(:install) do
        bin.install "console-ir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ashfaaq98/ocsf-console-ir/releases/download/v0.1.0/console-ir_0.1.0_Linux_amd64.tar.gz"
      sha256 "afdb1862c01d560d7808c0cff128a37f11a33c4a6cc59f484c102afd5977459d"
      define_method(:install) do
        bin.install "console-ir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ashfaaq98/ocsf-console-ir/releases/download/v0.1.0/console-ir_0.1.0_Linux_arm64.tar.gz"
      sha256 "b1eb78240587e67405d0a40522500033c5b3ee59fcd1c774b19a854368bf7373"
      define_method(:install) do
        bin.install "console-ir"
      end
    end
  end

  test do
    system "#{bin}/console-ir", "--version"
  end
end
