# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConsoleIr < Formula
  desc "Terminal-first OCSF-native incident response manager for security analysts"
  homepage "https://github.com/Ashfaaq98/ocsf-console-ir"
  version "0.1.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ashfaaq98/ocsf-console-ir/releases/download/v0.1.0/console-ir_0.1.0_macOS_amd64.tar.gz"
      sha256 "9d4817322b57bdff90e2af846bd622209a15f51cdaa0bfd9b2b3e5e19eedd96d"

      define_method(:install) do
        bin.install "console-ir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ashfaaq98/ocsf-console-ir/releases/download/v0.1.0/console-ir_0.1.0_macOS_arm64.tar.gz"
      sha256 "2328a082fcac347dd0058abcf9cdeade4453f197ba4aff5571e1f95a9cb162c7"

      define_method(:install) do
        bin.install "console-ir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ashfaaq98/ocsf-console-ir/releases/download/v0.1.0/console-ir_0.1.0_Linux_amd64.tar.gz"
      sha256 "cb10667d179e21bfe51f26612a9c18936d9dd639596facd9376f20d8e63f8828"
      define_method(:install) do
        bin.install "console-ir"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ashfaaq98/ocsf-console-ir/releases/download/v0.1.0/console-ir_0.1.0_Linux_arm64.tar.gz"
      sha256 "65d8f2f0ccf6d6e958e9d6ab92637a51998feb31f39720ee4b5a48e2df99a141"
      define_method(:install) do
        bin.install "console-ir"
      end
    end
  end

  test do
    system "#{bin}/console-ir", "--version"
  end
end
